trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Build Variables' #This is a variable group created in DevOps under library - needed to pass the resource Ids etc

steps:
- task: AzureImageBuilderTask@1
  inputs:
    managedIdentity: '$(managedIdentity)'
    imageSource: 'marketplace'
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:19h1-evd'
    baseImagePubOfferSku: 'MicrosoftWindowsDesktop:Windows-10:20h2-evd'
    provisioner: 'powershell'
    packagePath: 'scripts'
    inlineScript: '''& set-executionpolicy remotesigned -scope Process -Force; c:\BuildArtifacts\imageBuildcustomisation.ps1'''
    storageAccountName: '$(storageAccountName)'
    distributeType: 'sig'
    galleryImageId: '$(sharedGalleryImage)'
    replicationRegions: 'WestUS'
    ibSubscription: '$(subscriptionId)'
    ibAzureResourceGroup: '$(resourceGroup)'
    ibLocation: '$(location)'
